### ISSUE TITLE
standalone.bat runtime error

### ISSUE THREAD

**Issue by StygianSmash** [frostazy/QRLibrarian#1]
``` bash
12:56:30,264 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.serverManagement.controller.management.http: org.jboss.msc.service.StartException in service jboss.serverManagement.controller.management.http: WFLYSRV0083: Failed to start the http-interface service
        at org.jboss.as.server.mgmt.UndertowHttpManagementService.start(UndertowHttpManagementService.java:269)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
        at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.net.BindException: Address already in use: bind
        at org.jboss.as.domain.http.server.ManagementHttpServer.start(ManagementHttpServer.java:160)
        at org.jboss.as.server.mgmt.UndertowHttpManagementService.start(UndertowHttpManagementService.java:235)
        ... 5 more
Caused by: java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:67)
        at org.xnio.nio.NioXnioWorker.createTcpConnectionServer(NioXnioWorker.java:182)
        at org.xnio.XnioWorker.createStreamConnectionServer(XnioWorker.java:243)
        at org.jboss.as.domain.http.server.ManagementHttpServer.start(ManagementHttpServer.java:147)
        ... 6 more
```

I got some wrong when run this bash `standalone.bat`

**Comment by ivytin** [comment]
U should Google first.
[Error starting JBoss 7.1.1 on Windows 7 64bit](http://stackoverflow.com/questions/17973025/error-starting-jboss-7-1-1-on-windows-7-64bit)

---

The owner of this repository said u must **delete** some important files by mistake. 

---

`UPDATE`
The owner is coming to your house for debugging

**Comment by StygianSmash** [comment]
Restart u PC will solve this problem.
